apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-app-memory
  namespace: default
  labels:
    app: nodejs-app
spec:
  maxReplicas: 10
  minReplicas: 7
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-app
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60